service: EnvyForgeIdentity-UserMgr

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-offline

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or falls back to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}
  table:
    user: ${opt:usertable, self:provider.table.user}
    tenant: ${opt:tenanttable, self:provider.table.tenant}
    order: ${opt:ordertable, self:provider.table.order}
    product: ${opt:producttable, self:provider.table.product}
  configdir:
    local: "../config/"
    dev: "./config/"
    prod: "./config/"
  region: ${self:provider.region}
  authdir: "../authMgr/"
  customauthdir: "../common/"
  orderdir: "../orderMgr/"
  productdir: "../productMgr/"
  sysregdir: "../sysReg/"
  tenantmgrdir: "../tenantMgr/"
  tenantregdir: "../tenantReg/"
  userdir: ""
  libsdir: "../../libs/"
  # Load our webpack config
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs12.x
  timeout: 30 #set timeout to 30 seconds
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "cognito-idp:*"
        - "iam:CreatePolicy"
        - "iam:CreateRole"
        - "iam:DeleteRole"
        - "iam:DeletePolicy"
        - "iam:AttachRolePolicy"
        - "iam:DetachRolePolicy"
        - "lambda:InvokeFunction"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "iam:PassRole"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "cognito-identity:*"
      Resource: "*"
  stage: dev
  region: ${opt:region, file(../common/common.yml):${self:custom.stage}.region}
  table:
    user: ${self:custom.stage}-SaaS-user
    tenant: ${self:custom.stage}-SaaS-tenant
    order: ${self:custom.stage}-SaaS-order
    product: ${self:custom.stage}-SaaS-product
  environment:
    stage: ${self:custom.stage}
    region: ${self:custom.region}

    USER_TABLE: ${self:custom.table.user}
    TENANT_TABLE: ${self:custom.table.tenant}
    ORDER_TABLE: ${self:custom.table.order}
    PRODUCT_TABLE: ${self:custom.table.product}

    restApiId:
      "Fn::ImportValue": ${self:custom.stage}-EnvyForgeIdentityApiRestApiId
    apiURL: ${file(../common/common.yml):${self:custom.stage}.apiURL, file(../common/common.yml):dev.apiURL}
    PROJECT_NAME: ${cf:EnvyForgeIdentity-Common-${self:custom.stage}.ProjectName,'EnvyForgeIdentity'}
    serviceURL: ${file(../common/common.yml):${self:custom.stage}.serviceURL, file(../common/common.yml):dev.serviceURL}

    SNS_ROLE_ARN:
      "Fn::ImportValue": ${self:custom.stage}-EnvyForgeIdentitySNSRoleArn

    NODE_CONFIG_DIR: ${self:custom.configdir.${self:custom.stage}}

  # define share ApiGateway
  apiGateway:
    restApiId:
      "Fn::ImportValue": ${self:custom.stage}-EnvyForgeIdentityApiRestApiId
    restApiRootResourceId:
      "Fn::ImportValue": ${self:custom.stage}-EnvyForgeIdentityApiRestApiRootResourceId

functions:
  - ${file(${self:custom.userdir}userMgr-functions.yml)}
  #- ${file(${self:custom.customauthdir}customAuth-functions.yml)}

resources:
  Resources:
    UserDB:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 10
          WriteCapacityUnits: 10
        TableName: ${self:custom.table.user}
        GlobalSecondaryIndexes:
          - IndexName: UserNameIndex
            KeySchema:
              - AttributeName: id
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 10
              WriteCapacityUnits: 10
